import os

PWD = os.getcwd()
PREPROCESSING_TOOLS_DIRECTORY = "/preprocessing_tools/"

CORENLP_DIRECTORY = PWD+PREPROCESSING_TOOLS_DIRECTORY+"corenlp/"
CORENLP_TOOL_DIRECTORY = CORENLP_DIRECTORY + "stanford_corenlp_tool"

TRUECASE_INPUT_FILE = "truecase"
TRUECASE_GENERATED_FILE = "truecase.xml"

CORENLP_INPUT = CORENLP_DIRECTORY + "corenlp_input"
CORENLP_GENERATED_FILE = CORENLP_DIRECTORY + "corenlp_input.xml"
CONFIG_CORENLP = CORENLP_DIRECTORY + "CONFIG_CORENLP"

EXTENDER_NER_DIRECTORY = PWD+PREPROCESSING_TOOLS_DIRECTORY+"extended_ner/"

DISAMBIGUATOR_DIRECTORY = PWD+PREPROCESSING_TOOLS_DIRECTORY+"category_disambiguator/"

MYSQL_FOOD_CONFIG_FILE = EXTENDER_NER_DIRECTORY + "food/api/config.ini"

ABBREVIATION_CHECKER = PWD + PREPROCESSING_TOOLS_DIRECTORY +'abbreviation_checker/'
RULES_DIRECTORY = ABBREVIATION_CHECKER +'rules/'
FILENAME = RULES_DIRECTORY + 'filelist'

# SPELL CHECKER
SPELL_CHECKER = PWD + PREPROCESSING_TOOLS_DIRECTORY +'spell_checker/'
PWL_FILE = SPELL_CHECKER + "all_words.txt"
OTHER_WORDS_FILE = SPELL_CHECKER + "other_words"

NORMALIZER = PWD + PREPROCESSING_TOOLS_DIRECTORY +'normalizer/'
WORDS_FILE = NORMALIZER + "rules/rule"