import os

PWD=os.getcwd()
PREPROCESSING_TOOLS_DIRECTORY = "/preprocessing_tools/"

CORENLP_DIRECTORY = PWD+PREPROCESSING_TOOLS_DIRECTORY+"corenlp/"
CORENLP_GENERATED_FILE = CORENLP_DIRECTORY + "corenlp_input.xml"

EXTENDED_NER_DIRECTORY = PWD+PREPROCESSING_TOOLS_DIRECTORY+"extended_ner/"

# TRAVEL CONSTANTS 
EXTENDED_NER_DIRECTORY = EXTENDED_NER_DIRECTORY + "travel/"
EXTENDED_NER_RULES_DIRECTORY = EXTENDED_NER_DIRECTORY + "ner_rules/"

CSV_FILE_EXTENSION = ".csv"

CLASS_RULES = EXTENDED_NER_RULES_DIRECTORY + "class/rules/"
CLASS_SEEDLIST = EXTENDED_NER_RULES_DIRECTORY + "class/seedlist/"
NO_CLASS_FILE = CLASS_RULES + "no_class"

WEIGHT_RULES = EXTENDED_NER_RULES_DIRECTORY + "weight/rules/"
WEIGHT_EXIST_FILE = WEIGHT_RULES + "weights"

AMOUNT_RULES = EXTENDED_NER_RULES_DIRECTORY + "amount/rules/"
AMOUNT_EXIST_FILE = AMOUNT_RULES + "amounts"
CURRENCY_LIST_FILE = AMOUNT_RULES + "currency_list"
CURRENCY_DIRECTORY = AMOUNT_RULES + "currency/"
VALUE_LIST_FILE = AMOUNT_RULES + "value_list"
VALUE_DIRECTORY = AMOUNT_RULES + "value/"

RANGE_RULES_FILE=EXTENDED_NER_RULES_DIRECTORY+"range_rules"

TRAIN_QUOTA_RULES = EXTENDED_NER_RULES_DIRECTORY + "train_quota/rules/"
TRAIN_QUOTA_EXIST_FILE = TRAIN_QUOTA_RULES + "train_quota"

SEAT_PREFERENCE_RULES = EXTENDED_NER_RULES_DIRECTORY + "seat_preference/rules/"
SEAT_PREFERENCE_SEEDLIST = EXTENDED_NER_RULES_DIRECTORY + "seat_preference/seedlist/"
NO_SEAT_PREFERENCE_FILE = SEAT_PREFERENCE_RULES + "no_seat"

NUM_STOPS_RULES = EXTENDED_NER_RULES_DIRECTORY + "num_stops/rules/"
NUM_STOPS_FILE = NUM_STOPS_RULES + "num_stops"+CSV_FILE_EXTENSION

NUM_SEATS_RULES = EXTENDED_NER_RULES_DIRECTORY + "num_seats/rules/"
NUM_SEAT_IDENTIFIER = NUM_SEATS_RULES + "num_seats"+CSV_FILE_EXTENSION
NUM_SEAT_LIST = NUM_SEATS_RULES + "seat_list"+CSV_FILE_EXTENSION

TRAVEL_TYPE_RULES = EXTENDED_NER_RULES_DIRECTORY + "travel_type/rules/"
TRAVEL_TYPE_FILE = TRAVEL_TYPE_RULES + "travel_type"+CSV_FILE_EXTENSION

TRANSPORT_RULES = EXTENDED_NER_RULES_DIRECTORY + "transport/rules/"
TRANSPORT_LIST_FILE = EXTENDED_NER_RULES_DIRECTORY + "transport/transport_list"

TRANSACTION_RULES = EXTENDED_NER_RULES_DIRECTORY + "transaction/rules/"
TRANSACTION_LIST_FILE = EXTENDED_NER_RULES_DIRECTORY + "transaction/transaction_list"
