import os
from FILE_CONSTANTS import *


CSV_FILE_EXTENSION = ".csv"

DISAMBIGUATOR_RULES_DIRECTORY = DISAMBIGUATOR_DIRECTORY + "rules/"
DISAMBIGUATOR_LOCATION_RULES = DISAMBIGUATOR_RULES_DIRECTORY + "location/"


DISAMBIGUATOR_LOCATION_KEYWORDS = DISAMBIGUATOR_LOCATION_RULES + "keywords/"
DISAMBIGUATOR_LOCATION_PREPOSITIONS = DISAMBIGUATOR_LOCATION_RULES + "prepositions/"
DISAMBIGUATOR_LOCATION_VERBS = DISAMBIGUATOR_LOCATION_RULES + "verbs/"

DISAMBIGUATOR_LOCATION_SOURCE_KEYWORDS = DISAMBIGUATOR_LOCATION_KEYWORDS + "source_keywords"+CSV_FILE_EXTENSION
DISAMBIGUATOR_LOCATION_DESTINATION_KEYWORDS = DISAMBIGUATOR_LOCATION_KEYWORDS + "destination_keywords"+CSV_FILE_EXTENSION

DISAMBIGUATOR_LOCATION_SOURCE_PREPOSITIONS = DISAMBIGUATOR_LOCATION_PREPOSITIONS + "source_prep"+CSV_FILE_EXTENSION
DISAMBIGUATOR_LOCATION_DESTINATION_PREPOSITIONS = DISAMBIGUATOR_LOCATION_PREPOSITIONS + "destination_prep"+CSV_FILE_EXTENSION

DISAMBIGUATOR_LOCATION_SOURCE_VERB = DISAMBIGUATOR_LOCATION_VERBS + "source_verb"+CSV_FILE_EXTENSION
DISAMBIGUATOR_LOCATION_DESTINATION_VERB = DISAMBIGUATOR_LOCATION_VERBS + "destination_verb"+CSV_FILE_EXTENSION

DISAMBIGUATOR_DATE_RULES = DISAMBIGUATOR_RULES_DIRECTORY + "date/"
DISAMBIGUATOR_DATE_PREPOSITIONS = DISAMBIGUATOR_DATE_RULES + "prepositions/"
DISAMBIGUATOR_DATE_VERBS = DISAMBIGUATOR_DATE_RULES + "verbs/"

DISAMBIGUATOR_DATE_RANGE_PREPOSITIONS = DISAMBIGUATOR_DATE_PREPOSITIONS + "range_preposition" + CSV_FILE_EXTENSION
DISAMBIGUATOR_DATE_START_PREPOSITIONS = DISAMBIGUATOR_DATE_PREPOSITIONS + "start_preposition" + CSV_FILE_EXTENSION
DISAMBIGUATOR_DATE_END_PREPOSITIONS = DISAMBIGUATOR_DATE_PREPOSITIONS + "end_preposition" + CSV_FILE_EXTENSION
DISAMBIGUATOR_DATE_START_VERBS = DISAMBIGUATOR_DATE_VERBS + "start_verb" + CSV_FILE_EXTENSION
DISAMBIGUATOR_DATE_END_VERBS = DISAMBIGUATOR_DATE_VERBS + "end_verb" + CSV_FILE_EXTENSION
